from __future__ import annotations

SCENE_GRAPH_NODE_SCENE = "scene"
SCENE_GRAPH_NODE_TAKE = "take"
SCENE_GRAPH_NODE_ASSET = "asset"
SCENE_GRAPH_NODE_NOTE = "note"

SCENE_GRAPH_EDGE_CONTAINS = "contains"
SCENE_GRAPH_EDGE_FOLLOWS = "follows"
SCENE_GRAPH_EDGE_SEMANTIC_MATCH = "semantic_match"
SCENE_GRAPH_EDGE_ALT_TAKE = "alt_take"
SCENE_GRAPH_EDGE_REFERENCES = "references"

SCENE_GRAPH_NODE_TYPES: tuple[str, ...] = (
    SCENE_GRAPH_NODE_SCENE,
    SCENE_GRAPH_NODE_TAKE,
    SCENE_GRAPH_NODE_ASSET,
    SCENE_GRAPH_NODE_NOTE,
)
SCENE_GRAPH_EDGE_TYPES: tuple[str, ...] = (
    SCENE_GRAPH_EDGE_CONTAINS,
    SCENE_GRAPH_EDGE_FOLLOWS,
    SCENE_GRAPH_EDGE_SEMANTIC_MATCH,
    SCENE_GRAPH_EDGE_ALT_TAKE,
    SCENE_GRAPH_EDGE_REFERENCES,
)

SCENE_GRAPH_NODE_TYPE_SET = frozenset(SCENE_GRAPH_NODE_TYPES)
SCENE_GRAPH_EDGE_TYPE_SET = frozenset(SCENE_GRAPH_EDGE_TYPES)
