#!/bin/bash
# MARKER_204.3: Install notification hooks in all agent worktrees.
#
# Claude Code agents: PreToolUse hook → check_notifications.sh
# Vibe agents: prints PRETOOL_HOOK setup instructions (env-var based, not settings.json)
#
# Usage:
#   bash scripts/install_notification_hooks.sh
#   bash scripts/install_notification_hooks.sh --dry-run
#
# Claude Code agents (8): Alpha, Beta, Gamma, Delta, Epsilon, Zeta, Eta, Commander
# Vibe agents (3): Mistral-1, Mistral-2, Mistral-3

set -eo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKTREES_DIR="$(cd "$REPO_ROOT/../" && pwd)"

DRY_RUN=false
[ "${1:-}" = "--dry-run" ] && DRY_RUN=true

# Claude Code agents: "ROLE:worktree" pairs
CLAUDE_CODE_AGENTS=(
    "Alpha:cut-engine"
    "Beta:cut-media"
    "Gamma:cut-ux"
    "Delta:cut-qa"
    "Epsilon:cut-qa-2"
    "Zeta:harness"
    "Eta:harness-eta"
    "Commander:pedantic-bell"
)

# Vibe agents: "ROLE:worktree" pairs (use check_opencode_signals.sh via PRETOOL_HOOK)
VIBE_AGENTS=(
    "Mistral-1:weather-mistral-1"
    "Mistral-2:cut-qa-5"
    "Mistral-3:weather-mistral-2"
)

echo "MARKER_204.3: Installing notification hooks"
echo "Worktrees dir: $WORKTREES_DIR"
echo "Dry run: $DRY_RUN"
echo ""

INSTALLED=0
SKIPPED=0
ERRORS=0

install_claude_hook() {
    local role="$1"
    local worktree="$2"
    local settings_path="$WORKTREES_DIR/$worktree/.claude/settings.json"

    if [ ! -f "$settings_path" ]; then
        echo "  [SKIP] $role ($worktree): settings.json not found at $settings_path"
        SKIPPED=$((SKIPPED + 1))
        return
    fi

    # Check if hook already installed
    if python3 -c "
import json, sys
with open('$settings_path') as f:
    s = json.load(f)
hooks = s.get('hooks', {}).get('PreToolUse', [])
for h in hooks:
    for inner in h.get('hooks', []):
        if 'check_notifications' in inner.get('command', ''):
            sys.exit(0)  # already installed
sys.exit(1)  # not found
" 2>/dev/null; then
        echo "  [SKIP] $role ($worktree): hook already installed"
        SKIPPED=$((SKIPPED + 1))
        return
    fi

    if $DRY_RUN; then
        echo "  [DRY]  $role ($worktree): would add PreToolUse hook (check_notifications.sh)"
        return
    fi

    # Add PreToolUse hook via Python (safe JSON merge)
    python3 - "$settings_path" "$role" <<'PYEOF'
import json, sys, os

settings_path = sys.argv[1]
role = sys.argv[2]

with open(settings_path) as f:
    settings = json.load(f)

hooks = settings.setdefault("hooks", {})
pre_hooks = hooks.setdefault("PreToolUse", [])

new_hook = {
    "matcher": "",
    "hooks": [
        {
            "type": "command",
            "command": f"bash scripts/check_notifications.sh {role} 2>/dev/null || true"
        }
    ]
}
pre_hooks.append(new_hook)

# Write back (pretty-print, 2-space indent to match existing style)
with open(settings_path, "w") as f:
    json.dump(settings, f, indent=2, ensure_ascii=False)
    f.write("\n")

print(f"OK")
PYEOF

    if [ $? -eq 0 ]; then
        echo "  [OK]   $role ($worktree): PreToolUse hook installed"
        INSTALLED=$((INSTALLED + 1))
    else
        echo "  [ERR]  $role ($worktree): failed to update settings.json"
        ERRORS=$((ERRORS + 1))
    fi
}

install_vibe_hook() {
    local role="$1"
    local worktree="$2"
    local settings_path="$WORKTREES_DIR/$worktree/.claude/settings.json"

    # Vibe uses PRETOOL_HOOK env var — not settings.json
    # But we can write a .env file or a launch script for convenience

    if $DRY_RUN; then
        echo "  [DRY]  $role ($worktree): Vibe — PRETOOL_HOOK via env var (no settings.json hook)"
        return
    fi

    # Ensure .claude dir exists (for future settings)
    local claude_dir="$WORKTREES_DIR/$worktree/.claude"
    mkdir -p "$claude_dir"

    # Write launch helper script for this Vibe agent
    local launch_script="$WORKTREES_DIR/$worktree/launch_vibe.sh"
    cat > "$launch_script" <<LAUNCH
#!/bin/bash
# Auto-generated by install_notification_hooks.sh
# Launch Vibe with VETKA signal delivery for role: $role
export VETKA_AGENT_ROLE="$role"
export PRETOOL_HOOK="bash scripts/check_opencode_signals.sh"
echo "[launch_vibe] Starting Vibe as $role with signal delivery enabled"
exec vibe "\$@"
LAUNCH
    chmod +x "$launch_script"
    echo "  [OK]   $role ($worktree): launch_vibe.sh written (PRETOOL_HOOK pre-set)"
    INSTALLED=$((INSTALLED + 1))
}

echo "── Claude Code agents ─────────────────────────────────"
for entry in "${CLAUDE_CODE_AGENTS[@]}"; do
    role="${entry%%:*}"
    worktree="${entry##*:}"
    install_claude_hook "$role" "$worktree"
done

echo ""
echo "── Vibe agents ────────────────────────────────────────"
for entry in "${VIBE_AGENTS[@]}"; do
    role="${entry%%:*}"
    worktree="${entry##*:}"
    install_vibe_hook "$role" "$worktree"
done

echo ""
echo "Done: $INSTALLED installed, $SKIPPED skipped, $ERRORS errors"

# Ensure signal directories exist
mkdir -p "$HOME/.claude/signals"
mkdir -p "$HOME/.vetka/signals"
echo "Signal dirs: ~/.claude/signals/ and ~/.vetka/signals/ (created if missing)"
