"""
MARKER_ZETA.D3: CLAUDE.md Generator — auto-generate per-worktree agent instructions.

Reads:
  - agent_registry.yaml (D1) — role definitions
  - Task board state (optional, via MCP)

Writes:
  - .claude/worktrees/<worktree>/CLAUDE.md for each role

Usage:
    # Dry-run (print to stdout, no file writes)
    python -m src.tools.generate_claude_md --dry-run

    # Generate for specific role
    python -m src.tools.generate_claude_md --role Alpha --dry-run

    # Generate all and write to disk
    python -m src.tools.generate_claude_md --all

    # As a module import
    from src.tools.generate_claude_md import generate_claude_md
    content = generate_claude_md("Alpha")
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import jinja2

from src.services.agent_registry import AgentRegistry, AgentRole

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
_TEMPLATE_PATH = _PROJECT_ROOT / "data" / "templates" / "claude_md_template.j2"
_REGISTRY_PATH = _PROJECT_ROOT / "data" / "templates" / "agent_registry.yaml"
_WORKTREES_DIR = _PROJECT_ROOT / ".claude" / "worktrees"

# MARKER_ZB_ROOT_GENERIC: Generic content for root CLAUDE.md.
# Written by generate_all() after every post-merge regen.
# Must contain no role-specific instructions — visible to ALL agents.
_GENERIC_ROOT_CLAUDE_MD = """\
# VETKA Project — All Agents
# Auto-generated by generate_claude_md.py | {generated_at}
# DO NOT EDIT — overwritten on every post-merge hook run.

## Start Here
```
1. mcp__vetka__vetka_session_init role=<YourCallsign>
   → returns: role_context, tasks, docs, predecessor advice, protocol guards
2. mcp__vetka__vetka_task_board action=list project_id=cut filter_status=pending
3. Claim → Work → action=complete task_id=<id> branch=<your-branch>
```

`action=complete` = auto-stage + commit + close task. NEVER `git add`/`git commit` manually.

## Non-Negotiable Rules (all roles, no exceptions)
- NEVER raw `git merge` — always use `vetka_task_board action=merge_request`
- NEVER commit to main
- NEVER touch files outside your `role_context.owned_paths`
- Only Commander (domain=architect, worktree=pedantic-bell) has merge authority
- QA gate (Delta/Epsilon) must verify before ANY merge to main

## Fleet Pipeline
claim → work → complete (done_worktree) → QA verify → Commander merge_request → promote_to_main

## Roles
- Alpha/Beta/Gamma (Sonnet) — feature agents in domain worktrees
- Delta/Epsilon (Sonnet) — QA gate, verify before merge
- Zeta/Eta (Sonnet) — infra/harness support
- Commander (Opus) — architect, merge authority, dispatch
"""

# MARKER_197.SLIM: Dead helpers removed — predecessor/docs/feedback now come from session_init


def _get_claude_projects_dir(worktree_dir: Path) -> Path:
    """MARKER_195.20b: Get ~/.claude/projects/<sanitized-path>/ for a worktree.

    Claude Code reads CLAUDE.md from both project root AND ~/.claude/projects/.
    Writing role-specific content here avoids git conflicts entirely —
    the file is never tracked, never committed, never conflicts on pull.

    Claude Code sanitizes paths: /a_b/c.d → -a-b-c-d
    (replaces /, _, . with -)
    """
    sanitized = re.sub(r"[/_.]", "-", str(worktree_dir.resolve()))
    return Path.home() / ".claude" / "projects" / sanitized


def _load_template(template_path: Optional[Path] = None) -> jinja2.Template:
    """Load Jinja2 template from disk."""
    path = template_path or _TEMPLATE_PATH
    with open(path, "r", encoding="utf-8") as f:
        return jinja2.Template(f.read(), undefined=jinja2.StrictUndefined)


def generate_claude_md(
    callsign: str,
    registry: Optional[AgentRegistry] = None,
    template: Optional[jinja2.Template] = None,
    pending_tasks: Optional[list[dict]] = None,
) -> Optional[str]:
    """MARKER_197.SLIM: Generate minimal CLAUDE.md — thin routing stub to session_init.

    CLAUDE.md is now a bootstrap file only. All dynamic context (owned_paths,
    predecessor advice, key docs, pending tasks) comes from session_init's
    role_context — the universal JSON contract for any coding tool
    (Claude Code, Codex, Gemini, Cursor, MCC, Mycelium).

    Args:
        callsign: Agent callsign (Alpha, Beta, Gamma, Delta, Commander, Zeta, Epsilon)
        registry: AgentRegistry instance (loaded from agent_registry.yaml if None)
        template: Jinja2 template (loaded from claude_md_template.j2 if None)
        pending_tasks: Deprecated, ignored. Tasks come from session_init.

    Returns:
        Generated CLAUDE.md content string, or None if callsign not found.
    """
    if registry is None:
        registry = AgentRegistry(_REGISTRY_PATH)
    if template is None:
        template = _load_template()

    role = registry.get_by_callsign(callsign)
    if role is None:
        logger.warning("Unknown callsign: %s", callsign)
        return None

    context = {
        "role": role,
        "generated_at": datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
    }

    rendered = template.render(**context)

    # MARKER_200.TOKEN_BUDGET: Warn if generated CLAUDE.md exceeds token budget.
    # Prevents template bloat creep. ~4 chars/token heuristic.
    _TOKEN_BUDGET = 500
    _estimated_tokens = len(rendered) // 4
    if _estimated_tokens > _TOKEN_BUDGET:
        logger.warning(
            "[generate_claude_md] %s: ~%d tokens (budget: %d) — consider trimming template",
            callsign, _estimated_tokens, _TOKEN_BUDGET,
        )

    return rendered


def write_claude_md(
    callsign: str,
    output_dir: Optional[Path] = None,
    **kwargs,
) -> Optional[Path]:
    """Generate and write CLAUDE.md to disk.

    Args:
        callsign: Agent callsign
        output_dir: Override output directory (default: .claude/worktrees/<worktree>/)
        **kwargs: Forwarded to generate_claude_md()

    Returns:
        Path to written file, or None if generation failed.
    """
    registry = kwargs.pop("registry", None) or AgentRegistry(_REGISTRY_PATH)
    role = registry.get_by_callsign(callsign)
    if role is None:
        return None

    content = generate_claude_md(callsign, registry=registry, **kwargs)
    if content is None:
        return None

    if output_dir is None:
        # MARKER_195.22: Dual-write for single-role generation too.
        worktree_dir = _WORKTREES_DIR / role.worktree
        output_dir = _get_claude_projects_dir(worktree_dir)

    output_dir.mkdir(parents=True, exist_ok=True)
    output_path = output_dir / "CLAUDE.md"
    output_path.write_text(content, encoding="utf-8")
    logger.info("[generate_claude_md] Wrote %s (%d bytes)", output_path, len(content))

    # MARKER_195.22: Also write to local worktree (prevents stale identity bug)
    local_dir = _WORKTREES_DIR / role.worktree
    if local_dir.exists() and local_dir != output_dir:
        local_path = local_dir / "CLAUDE.md"
        local_path.write_text(content, encoding="utf-8")
        logger.info("[generate_claude_md] Wrote local %s (%d bytes)", local_path, len(content))

    return output_path


def generate_all(dry_run: bool = False, output_base: Optional[Path] = None) -> dict[str, str]:
    """Generate CLAUDE.md for all roles.

    Args:
        dry_run: If True, don't write files
        output_base: Override base directory for worktree CLAUDE.md files

    Returns:
        Dict of callsign -> generated content
    """
    registry = AgentRegistry(_REGISTRY_PATH)
    template = _load_template()
    results = {}

    for role in registry.roles:
        content = generate_claude_md(role.callsign, registry=registry, template=template)
        if content is None:
            continue
        results[role.callsign] = content

        if not dry_run:
            # MARKER_195.22: Dual-write — both locations so Claude Code always finds the role.
            # Priority 1: ~/.claude/projects/ (Claude Code discovery, never conflicts with git)
            # MARKER_ZB_ROOT_GENERIC: Don't write architect config to shared ~/.claude/projects/
            # root path — only to the dedicated pedantic-bell worktree location.
            # Guard only applies to the ~/.claude/projects/ path (not output_base test mode).
            worktree_dir = (output_base or _WORKTREES_DIR) / role.worktree
            _skip_shared_write = (not output_base) and role.domain == "architect"
            if not _skip_shared_write:
                out_dir = _get_claude_projects_dir(worktree_dir) if not output_base else worktree_dir
                out_dir.mkdir(parents=True, exist_ok=True)
                (out_dir / "CLAUDE.md").write_text(content, encoding="utf-8")
                logger.info("[generate_claude_md] Wrote %s/CLAUDE.md", out_dir)

            # Priority 2: .claude/worktrees/<name>/CLAUDE.md (local override, takes priority)
            # Without this, stale generic files cause identity confusion (Gamma→Commander bug).
            if not output_base:
                local_dir = _WORKTREES_DIR / role.worktree
                if local_dir.exists():
                    (local_dir / "CLAUDE.md").write_text(content, encoding="utf-8")
                    logger.info("[generate_claude_md] Wrote local %s/CLAUDE.md", local_dir)

                    # MARKER_201.NOTIFY: Generate settings.json with inbox hook
                    _write_settings_json(local_dir)

    # MARKER_ZB_ROOT_GENERIC: Overwrite root CLAUDE.md with generic content after every regen.
    # Prevents merge-infection: when agent branches commit their role CLAUDE.md and get merged,
    # the post-merge hook immediately restores the generic version.
    if not dry_run and not output_base:
        root_claude = _PROJECT_ROOT / "CLAUDE.md"
        generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        root_claude.write_text(
            _GENERIC_ROOT_CLAUDE_MD.format(generated_at=generated_at),
            encoding="utf-8",
        )
        logger.info("[generate_claude_md] Wrote generic root CLAUDE.md (%s)", root_claude)

    return results


# MARKER_201.NOTIFY: Settings.json generation for agent inbox hooks
# MARKER_204.FIX: Correct nested format — Claude Code rejects flat {"matcher","command"} entries
_INBOX_HOOK_ENTRY = {
    "matcher": "",
    "hooks": [{"type": "command", "command": "bash scripts/check_agent_inbox.sh 2>/dev/null || true"}],
}


def _hook_has_inbox(hook: dict) -> bool:
    """Detect inbox hook in both old flat format and new nested format."""
    if "check_agent_inbox" in hook.get("command", ""):
        return True
    for inner in hook.get("hooks", []):
        if "check_agent_inbox" in inner.get("command", ""):
            return True
    return False


def _write_settings_json(worktree_dir: Path):
    """Write or merge .claude/settings.json with inbox hook for a worktree.

    Always removes stale flat-format entries and ensures correct nested format exists.
    """
    settings_dir = worktree_dir / ".claude"
    settings_path = settings_dir / "settings.json"

    try:
        existing = {}
        if settings_path.exists():
            existing = json.loads(settings_path.read_text(encoding="utf-8"))

        hooks = existing.get("hooks", {})
        post_hooks = hooks.get("PostToolUse", [])

        # Remove all stale flat-format entries (missing "hooks" array)
        post_hooks = [h for h in post_hooks if "hooks" in h]

        # Add correct inbox hook if not already present
        if not any(_hook_has_inbox(h) for h in post_hooks):
            post_hooks.append(_INBOX_HOOK_ENTRY)

        hooks["PostToolUse"] = post_hooks
        existing["hooks"] = hooks

        settings_dir.mkdir(parents=True, exist_ok=True)
        settings_path.write_text(
            json.dumps(existing, indent=2, ensure_ascii=False) + "\n",
            encoding="utf-8",
        )
        logger.info("[generate_claude_md] Wrote %s (inbox hook)", settings_path)
    except Exception as e:
        logger.debug(f"[generate_claude_md] Settings.json write failed: {e}")


# ── CLI ─────────────────────────────────────────────────────


def main():
    parser = argparse.ArgumentParser(description="Generate per-worktree CLAUDE.md files")
    parser.add_argument("--role", type=str, help="Generate for specific callsign (Alpha, Beta, etc.)")
    parser.add_argument("--all", action="store_true", help="Generate for all roles")
    parser.add_argument("--dry-run", action="store_true", help="Print to stdout, don't write files")
    parser.add_argument("--output-dir", type=str, help="Override output directory")
    parser.add_argument("--post-merge", action="store_true",
                        help="MARKER_200.POST_MERGE: Generate all + run stale_check (for git hooks)")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(message)s")

    if args.post_merge:
        args.all = True  # --post-merge implies --all

    if not args.role and not args.all:
        parser.print_help()
        sys.exit(1)

    output_base = Path(args.output_dir) if args.output_dir else None

    if args.all:
        results = generate_all(dry_run=args.dry_run, output_base=output_base)
        for callsign, content in results.items():
            if args.dry_run:
                print(f"\n{'='*60}")
                print(f"  {callsign}")
                print(f"{'='*60}\n")
                print(content)
            else:
                print(f"Generated: {callsign}")
        print(f"\nTotal: {len(results)} files {'(dry-run)' if args.dry_run else 'written'}")

        # MARKER_200.POST_MERGE: Run stale_check after generating all CLAUDE.md
        if args.post_merge and not args.dry_run:
            try:
                from src.orchestration.task_board import get_task_board
                board = get_task_board()
                stale = board.stale_check(limit=30, auto_close=False)
                _count = stale.get("candidates_count", 0)
                if _count > 0:
                    print(f"\n[post-merge] {_count} potentially stale tasks found:")
                    for c in stale.get("candidates", [])[:5]:
                        print(f"  - {c.get('task_id', '?')}: {c.get('title', '?')[:60]}")
                else:
                    print("\n[post-merge] No stale tasks detected.")
            except Exception as e:
                print(f"\n[post-merge] stale_check skipped: {e}")
    else:
        content = generate_claude_md(args.role)
        if content is None:
            print(f"Error: Unknown callsign '{args.role}'", file=sys.stderr)
            sys.exit(1)
        if args.dry_run:
            print(content)
        else:
            path = write_claude_md(args.role, output_dir=output_base)
            print(f"Written: {path}")


if __name__ == "__main__":
    main()
